# Generated by Django 5.2.9 on 2025-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
