# Generated by Django 5.2.9 on 2025-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_title_alter_book_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
