# Generated by Django 5.2.9 on 2025-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
