# Generated by Django 5.2.9 on 2025-12-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_isbn_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='openlibrary_key',
        ),
    ]
