# Generated by Django 5.2.9 on 2025-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_openlibrary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Obálka knihy'),
        ),
    ]
