# Generated by Django 5.2.9 on 2025-12-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_pending_data_book_pending_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
