# Generated by Django 5.2.9 on 2025-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_author_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
