# Generated by Django 5.2.9 on 2025-12-09 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True,
                                      null=True,
                                      validators=[django.core.validators.MinValueValidator(1800),
                                                  django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
